title: Gabu.me!
timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

email: gabriel@gabu.me
description: >-
  Apenas mais um desenvolvedor latino americano sem
  bitcoin no banco.

baseurl: ""
url: ""

twitter_username: GabuMoreira
github_username:  GabuMoreira

markdown: kramdown
theme: minima
plugins:
- jekyll-feed
