title: Gabu.me
timezone: UTC-3
author: João Gabriel
lang: pt_BR

built-by: gabu

copyright:
  name: João Gabriel
  link: 'https://gabu.me'

email: gabriel@gabu.me
description: >-
  Apenas mais um desenvolvedor latino americano sem
  bitcoin no banco.

baseurl: ""
url: "https://gabu.me"
host: "gabu.me"
image: "/assets/img/logo.png"

paginate: 5
paginate_path: "/blog/page:num/"

sass:
  style: compressed

twitter_username: GabuMoreira
github_username:  GabuMoreira
#linkedin_username:  joaogmrodrigues

disqus:
  shortname: gabu-me

markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag