title: Gabu.me
timezone: UTC-3
author: João Gabriel
lang: pt_BR

built-by: gabu

copyright:
  name: João Gabriel
  link: 'https://gabu.me'

email: gabriel@gabu.me
description: >-
  Diário de bordo sobre desenvolvimento, tecnologia e coisas ágeis.

baseurl: ""
url: "https://gabu.me"
host: "gabu.me"
keywords: [tecnologia, gabu, devops, gabriel, desenvolvimento, blog]

paginate: 5
paginate_path: "/blog/page:num/"

sass:
  style: compressed

analytics: UA-145817473-1
tagmanager: GTM-5BZTL6W

social_links:
  twitter: GabuMoreira
  github: GabuMoreira
  linkedin: joaogmrodrigues

disqus:
  shortname: gabu-me

markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
