title: Gabu.me!
timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

email: gabriel@gabu.me
description: >-
  Apenas mais um desenvolvedor latino americano sem
  bitcoin no banco.

baseurl: ""
url: ""
paginate: 5
paginate_path: "/blog/page:num/"

#sass:
#  sass_dir: _sass

twitter_username: GabuMoreira
github_username:  GabuMoreira

markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
